version: '3'

tasks:
  run:
    cmds:
      - go run main.go

  build:
    cmds:
      - go build -o bin/main main.go

  build-image:
    cmds:
      - docker build -t sih-server -f deploy/Dockerfile .